// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd3Hue83XUE7KP-39ckTeNlSaWj7tEI9U',
    appId: '1:725233223963:web:b39866f2f557199ec92bbe',
    messagingSenderId: '725233223963',
    projectId: 'sgsystem-4bd12',
    authDomain: 'sgsystem-4bd12.firebaseapp.com',
    storageBucket: 'sgsystem-4bd12.appspot.com',
    measurementId: 'G-1M6SKP8RY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4J_FXPPvajCEC_HwfijZRbzQZNAMBkH0',
    appId: '1:725233223963:android:6e663ff4580a6c31c92bbe',
    messagingSenderId: '725233223963',
    projectId: 'sgsystem-4bd12',
    storageBucket: 'sgsystem-4bd12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UZ3_eEG3_F-J1dh0akGBfE3Hw5vv6_A',
    appId: '1:725233223963:ios:885122c510beda61c92bbe',
    messagingSenderId: '725233223963',
    projectId: 'sgsystem-4bd12',
    storageBucket: 'sgsystem-4bd12.appspot.com',
    iosBundleId: 'com.example.secureeeeeeeeeeeeeeee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7UZ3_eEG3_F-J1dh0akGBfE3Hw5vv6_A',
    appId: '1:725233223963:ios:885122c510beda61c92bbe',
    messagingSenderId: '725233223963',
    projectId: 'sgsystem-4bd12',
    storageBucket: 'sgsystem-4bd12.appspot.com',
    iosBundleId: 'com.example.secureeeeeeeeeeeeeeee',
  );
}
