// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD96a-iUZ8mzBDLnb11Qb3p-YedgbiMbCg',
    appId: '1:328719602514:web:8e2de960ff9410d884e08b',
    messagingSenderId: '328719602514',
    projectId: 'eeeee-6433d',
    authDomain: 'eeeee-6433d.firebaseapp.com',
    storageBucket: 'eeeee-6433d.appspot.com',
    measurementId: 'G-HKGY38JW4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeRIEBwvMoLIl0rJVaRIAmYVdRns2srLY',
    appId: '1:328719602514:android:903e83ef3505e78284e08b',
    messagingSenderId: '328719602514',
    projectId: 'eeeee-6433d',
    storageBucket: 'eeeee-6433d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85nGSHHwTZjQZIxVN3CagTSrVYvCsvaE',
    appId: '1:328719602514:ios:e6e51623a4bd057984e08b',
    messagingSenderId: '328719602514',
    projectId: 'eeeee-6433d',
    storageBucket: 'eeeee-6433d.appspot.com',
    iosBundleId: 'com.example.secureeeeeeeeeeeeeeee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85nGSHHwTZjQZIxVN3CagTSrVYvCsvaE',
    appId: '1:328719602514:ios:e6e51623a4bd057984e08b',
    messagingSenderId: '328719602514',
    projectId: 'eeeee-6433d',
    storageBucket: 'eeeee-6433d.appspot.com',
    iosBundleId: 'com.example.secureeeeeeeeeeeeeeee',
  );
}
